services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: my_secret_password
      POSTGRES_USER: university_library_db_admin
      POSTGRES_DB: university_library_db
    volumes:
      - university_library_db_volume:/var/lib/postgresql/data
volumes:
  university_library_db_volume:
    name: university_library_db_volume
